# Generated by Django 6.0.2 on 2026-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_reservation_checked_in_at_reservation_checked_out_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('OCCUPIED', 'Occupied'), ('DISABLED', 'Disabled')], default='AVAILABLE', max_length=10),
        ),
    ]
