# Generated by Django 6.0.2 on 2026-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_parkingslot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='owner_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
